config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  root 'tryouts#index'
  
get 'confirm' => 'tryouts#confirm', as: :tryouts_confirm

resources :profiles do
  resources :players
end

resources :tryouts do
  resources :players
end

  resources :guardianships
  resources :evaluations
  resources :guardians
  resources :coaches
  resources :players
  resources :users

  resources :tryouts do
    member do
get 'confirm' => 'tryouts#confirm'

    end	
 end

  resources :tryouts do
    resources :player_tryouts
  end

  resources :player_tryouts

end

app/models/tryout.rb
class Tryout < ActiveRecord::Base
  has_many :player_tryouts
end

app/controllers/tryouts_controller.rb
class TryoutsController < ApplicationController
  before_action :set_tryout , only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_profile!, only: [:index]
  #before_action :permissions , only: [:new, :edit :create,:update, :destroy]



#GEt /tryouts/confirm
  def confirm
  #@player_tryout = Player.player_tryouts.find(:tryout_id => @@current_tryout, :profile_id => current_profile.id)
  @player = Player.find(current_profile.id)
  @tryout = Tryout.find(params[:id])
  end


  # GET /tryouts
  # GET /tryouts.json
  def index
    @tryouts = Tryout.all
    #binding.pry
  end

  # GET /tryouts/1
  # GET /tryouts/1.json
  def show
  end

  # GET /tryouts/new
  def new
    #redirect_to tryouts_path if current_profile.user.type == "Player"
    @tryout = Tryout.new
  end

  # GET /tryouts/1/edit
  def edit

       #redirect_to tryouts_path if current_profile.user.type == "Player"

  end

  # POST /tryouts
  # POST /tryouts.json
  def create
#redirect_to tryouts_path if current_profile.user.type == "Player"
    @tryout = Tryout.new(tryout_params)

    respond_to do |format|
      if @tryout.save
        format.html { redirect_to @tryout, notice: 'Tryout was successfully created.' }
        format.json { render :show, status: :created, location: @tryout }
      else
        format.html { render :new }
        format.json { render json: @tryout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tryouts/1
  # PATCH/PUT /tryouts/1.json
  def update
#redirect_to tryouts_path if current_profile.user.type == "Player"
    respond_to do |format|
      if @tryout.update(tryout_params)
        format.html { redirect_to @tryout, notice: 'Tryout was successfully updated.' }
        format.json { render :show, status: :ok, location: @tryout }
      else
        format.html { render :edit }
        format.json { render json: @tryout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tryouts/1
  # DELETE /tryouts/1.json
  def destroy
	#redirect_to tryouts_path if current_profile.user.type == "Player"
    @tryout.destroy
    respond_to do |format|
      format.html { redirect_to tryouts_url, notice: 'Tryout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tryout
      @tryout = Tryout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tryout_params
      params.require(:tryout).permit(:date, :fee, :address1, :address2, :city, :state, :zip)
    end

    def permissions
	redirect_to tryouts_path if current_profile.user.type == "Player"
    end

end

app/helpers/tryouts_helper.rb
module TryoutsHelper
end

app/views/tryouts/_form.html.erb
<%= form_for(@tryout) do |f| %>
    <% if @tryout.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tryout.errors.count, "error") %> prohibited this tryout from being saved:</h2>

          <ul>
            <% @tryout.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col-md-12">
        <div class="field">
          <%= f.label :date %><br>
          <%= f.datetime_select :date, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="field">
          <%= f.label :fee %><br>
          <%= f.text_field :fee, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :address1 %><br>
          <%= f.text_field :address1, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :address2 %><br>
          <%= f.text_field :address2, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-6">
        <div></div>
        <div class="field">
          <%= f.label :city %><br>
          <%= f.text_field :city, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :state %><br>
          <%= f.select(:state,
                       ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL',
                        'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE',
                        'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
                        'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], {}, {:class => 'form-control'}) %>
        </div>
        <div class="field">
          <%= f.label :zip %><br>
          <%= f.number_field :zip, class: 'form-control' %>
        </div>
      </div>
    </div>
    <hr>
    <div class="actions">
      <%= f.submit "Submit", class: 'btn btn-primary pull-right' %>
    </div>
<% end %>

app/views/tryouts/confirm.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<%= link_to 'Pay with PayPal',  tryouts_path %> |
<%= link_to 'Edit', edit_player_path(current_profile.id) %> |
<%= link_to 'Back', tryouts_path %>

<div class="panel panel-primary">

  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Date:</strong>
          <%= @tryout.date.to_s(:long) %>
        </p>

        <p>
          <strong>Fee:</strong>
          $<%= number_with_precision(@tryout.fee, precision: 2) %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Address Line 1:</strong>
          <%= @tryout.address1 %>
        </p>

        <p>
          <strong>Address Line 2:</strong>
          <%= @tryout.address2 %>
        </p>

        <p>
          <strong>City:</strong>
          <%= @tryout.city %>
        </p>

        <p>
          <strong>State:</strong>
          <%= @tryout.state %>
        </p>

        <p>
          <strong>ZIP:</strong>
          <%= @tryout.zip %>
        </p>

<p>
  <strong>Profile_id:</strong>
  <%= @player.profile_id %>
</p>
<p>
  <strong>Type:</strong>
  <%= @player.type %>
</p>

<p>
  <strong>First name:</strong>
  <%= @player.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @player.last_name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @player.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @player.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @player.phone %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @player.gender %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @player.dob %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @player.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @player.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @player.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @player.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @player.zip %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @player.experience %>
</p>
      </div>
      <div class="col-md-4">

      </div>
    </div>
  </div>
</div>

app/views/tryouts/edit.html.erb
<h1>Editing Tryout</h1>

<%= render 'form' %>

<%= link_to 'Show', @tryout %> |
<%= link_to 'Back', tryouts_path %>

app/views/tryouts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Tryouts <%= link_to 'New Tryout', new_tryout_path, class: 'pull-right btn btn-success', style: 'color:white' %></h1>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-striped table-hover">
      <thead>
      <tr>
        <th>Date</th>
        <th>Fee</th>
        <th>Addr. Line 1</th>
        <th>Addr. Line 2</th>
        <th>City</th>
        <th>State</th>
        <th>ZIP</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @tryouts.each do |tryout| %>
          <tr>
            <td><%= link_to tryout.date.to_s(:long), tryout %></td>
            <td>$<%= number_with_precision(tryout.fee, precision: 2) %></td>
            <td><%= tryout.address1 %></td>
            <td><%= tryout.address2 %></td>
            <td><%= tryout.city %></td>
            <td><%= tryout.state %></td>
            <td><%= tryout.zip %></td>
            <td><%= link_to 'Edit', edit_tryout_path(tryout), class: 'btn btn-info' %></td>
            <td><%= link_to 'Destroy', tryout, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger', style: 'color:white' %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tryouts/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>New Tryout</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
    <%= link_to 'Back', tryouts_path, class:'btn btn-default pull-left' %>
  </div>
</div>

app/views/tryouts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<!-- <%= form_for([@tryout, PlayerTryout.new]) do |f| %>
  <p><%= f.submit "Register to this Tryout Online"%> </p>
<%end%> -->

<%= link_to 'Register to this Tryout Online',  player_tryouts_path(tryout_id: @tryout.id), method: :post %> |
<%= link_to 'Edit', edit_tryout_path(@tryout) %> |
<%= link_to 'Back', tryouts_path %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Tryout Details <%= link_to "Register", tryouts_path, class:'btn btn-success pull-right' %></h1>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Date:</strong>
          <%= @tryout.date.to_s(:long) %>
        </p>

        <p>
          <strong>Fee:</strong>
          $<%= number_with_precision(@tryout.fee, precision: 2) %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Address Line 1:</strong>
          <%= @tryout.address1 %>
        </p>

        <p>
          <strong>Address Line 2:</strong>
          <%= @tryout.address2 %>
        </p>

        <p>
          <strong>City:</strong>
          <%= @tryout.city %>
        </p>

        <p>
          <strong>State:</strong>
          <%= @tryout.state %>
        </p>

        <p>
          <strong>ZIP:</strong>
          <%= @tryout.zip %>
        </p>
      </div>
      <div class="col-md-4">

      </div>
    </div>
  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Registered Players</h1>
  </div>
  <div class="panel-body">
    <% @tryout.player_tryouts.each do |pt| %>
        <tr>
          <td><%= pt.player %></td>
        </tr>
    <% end %>
  </div>
</div>