config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  root 'tryouts#index'
  
get 'confirm' => 'tryouts#confirm', as: :tryouts_confirm

resources :profiles do
  resources :players
end

resources :tryouts do
  resources :players
end

  resources :guardianships
  resources :evaluations
  resources :guardians
  resources :coaches
  resources :players
  resources :users

  resources :tryouts do
    member do
get 'confirm' => 'tryouts#confirm'

    end	
 end

  resources :tryouts do
    resources :player_tryouts
  end

  resources :player_tryouts

end

app/models/coach.rb
class Coach < User
  has_many :evaluations
end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :coach
  belongs_to :player_tryout
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  has_many :guardianships
  belongs_to :user
end

app/models/guardianship.rb
class Guardianship < ActiveRecord::Base
  belongs_to :guardian
  belongs_to :player
end

app/models/player.rb
class Player < User
  has_many :player_tryouts, dependent: :destroy
  has_many :guardianships
end

app/models/player_tryout.rb
class PlayerTryout < ActiveRecord::Base
  belongs_to :player
  belongs_to :tryout
  has_many   :evaluations
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, #:confirmable

   has_one :user, dependent: :destroy
end

app/models/tryout.rb
class Tryout < ActiveRecord::Base
  has_many :player_tryouts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :guardian, dependent: :destroy
  belongs_to :profile
  has_attached_file :photo
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_params
      params[:coach]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_profile!
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:type, :first_name, :last_name, :username, :email, :phone, :gender, :dob, :address1, :address2, :city, :state, :zip, :experience, :profile_id, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/guardians_helper.rb
module GuardiansHelper
end

app/helpers/guardianships_helper.rb
module GuardianshipsHelper
end

app/helpers/player_tryouts_helper.rb
module PlayerTryoutsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tryouts_helper.rb
module TryoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Soccer Tryout Manager</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">


  <!-- Bootstrap Core CSS -->
  <link href="bootstrap.css" rel="stylesheet">
  <!-- Custom CSS -->
  <link href="heroic-features.css" rel="stylesheet">

</head>

<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<p class="navbar-text pull-right">
<% if profile_signed_in? %>
  Logged in as <strong><%= current_profile.email %></strong>.
  <%= link_to 'Edit profile', edit_profile_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_profile_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_profile_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_profile_session_path, :class => 'navbar-link'  %>
<% end %>



<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color:#336699">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Soccer Tryout Manager", tryouts_path, {:class => "navbar-brand", :style => "color:white"} %>

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container">


  <%= yield %>

  <!-- Footer -->
  <div class="navbar navbar-default navbar-fixed-bottom" style="background-color:#336699">
    <div class="container" style="padding-top: 10px">
      <p class="text-center" style="color: #9d9d9d;">Copyright &copy;
        <a style="color: #fff;" href="mailto:heileman@unm.edu?Subject=ECE%20595%20-%20Soccer%20Tryout%20Manager" target="_blank">
          <b><u>University of New Mexico</u></b></a> - Soccer Tryout Manager 2015</p>
    </div>
  </div>

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>
<script src="js/jquery.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

</body>

</html>